#!/bin/bash -xe

# link bio for front page
cp ./cv/bio/1st_short_en.md ./_includes/cv/about.md

# link profile pic
cp ./cv/shared/picture.jpg ./assets/img/prof_pic.jpg

# link bibliography and adapt for jekyll
cp ./cv/shared/publications.bib ./_bibliography/papers.bib
sed -i '1s/^/---\n---\n\n/' publications.bib

