name: Build Jekyll site
on:
 push:
   branches: ["master"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  jekyll:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    #- name: Build
    #  uses: ${{ vars.ACTIONS_REPO }}

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.1'
        bundler-cache: true
      env:
        RUNNER_TOOL_CACHE: /toolcache

    - name: Install and Build
      run: |
        npm install -g mermaid.cli
        stat assets/img/prof_pic.jpg
        ls -la cv/
        bundle exec jekyll build

    - name: Deploy
      uses: burnett01/rsync-deployments@7.1.0
      with:
        switches: -avzr --delete
        path: _site
        remote_path: ${{ vars.PAGES_PATH_PREFIX }}main
        remote_host: ${{ vars.SSH_HOST }}
        remote_user: ${{ vars.SSH_USER }}
        remote_key: ${{ secrets.SSH_KEY }}
        remote_key_pass: ${{ secrets.SSH_KEY_PASS }}
        
